### PR TITLE
100

### PR DESCRIPTION
**Pull request by centime**
Hi,

I see your 138 chars "alert(1)", and raise you with 105 :)

Before you include merge this PR, make sure to replace my ugly _'s and $'s with some fancy-looking katakana characters.

By the way, nice to meet you aemkei. I've always been greatly inspired by your work !

### CODE REVIEW

**Comment by centime** [comment]
Nevermind 105, here is 102 :)

([,ウ,,,,ア]=[]+{},[ネ,ホ,ヌ,セ,,ミ,ハ,ヘ,,
ヌ,_]=[!!ウ]+!ウ+ウ.ウ)[$=ア+ウ+_+ヘ+ネ+ホ+ヌ
+ア+ネ+ウ+ホ][$](ミ+ハ+セ+ホ+ネ+'(+!!ウ)')()

**Comment by aemkei** [comment]
Wow, how cool is that!!?!! ES6 FTW. Great work, @centime! 

BTW: To stay with Katakana, we should replace `$` with a Japanese char, eg. `ツ`

```js
([,ウ,,,,ア]=[]+{},[ネ,ホ,ヌ,セ,,ミ,ハ,ヘ,,ヌ,_]=
[!!ウ]+!ウ+ウ.ウ)[ツ=ア+ウ+_+ヘ+ネ+ホ+ヌ+
ア+ネ+ウ+ホ][ツ](ミ+ハ+セ+ホ+ネ+'(+!!ウ)')()
```

**Comment by aemkei** [comment]
Ps, are you on Twitter? Would love to give you some credits.

**Comment by centime** [comment]
In my rush to submit, I forgot two easy improvements, so here is yet another version: 100 chars.

Thanks for $'s replacement, would you have another for "_" ? I'm just being lazy here, but I let you chose it :)

**Comment by centime** [comment]
Never really got into twitter, nope.. As far as credit goes, I added myself to the list of thanks in the README.

Just point to my github and it'll be just fine !

**Comment by centime** [comment]
Btw, I think you could alos enjoy this: http://centime.org/reverJS/

**Comment by aemkei** [comment]
`ナ` is not used. 

Full set of chars: https://en.wikipedia.org/wiki/Katakana#Script

```
アイウエオ
カキクケコ
サシスセソ
タチツテト
ナニヌネノ
ハヒフヘホ
マミムメモ
ヤユヨ
ラリルレロ
ワヰヱヲ
```

**Comment by aemkei** [comment]
https://twitter.com/aemkei/status/887039288780705793

image

**Comment by centime** [comment]
Thank you for the credit, and keep up with the great js work you do !

**Pull request merged**
